name: fcl
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pysimplegui
  - opencv
  - pip:
      - torch
      - torchvision
      - torchaudio
      - imageio
      - transformers
